/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.ui;

import app.model.Cliente;
import app.model.Estoque;
import app.model.Funcionario;
import app.model.Peca;
import app.model.Servico;
import app.model.TipoDePeca;
import app.utils.Objetos;
import app.utils.SessaoUsuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henri
 */
public class GerenciarServicos extends javax.swing.JFrame {
    private final Funcionario usuario;
    private Servico servico;
    private Cliente cliente; //pra poupar um loop dentro da tabela
    private final ArrayList<Peca> pecas;
    /**
     * Creates new form GerenciarServicos
     */
    public GerenciarServicos() {
        usuario = SessaoUsuario.getInstancia().getUsuarioLogado();
        initComponents();
        carregaTabelaServicos(false);
        
        pecas = new ArrayList<>();

        jTFCliente.setEditable(false);
        jTFCliente.setText("");
        
        jTFVeiculo.setEditable(false);
        jTFVeiculo.setText("");
        
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        
        jFTFCPF.setEnabled(false);
        jButtonBusca.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFVeiculo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxPago = new javax.swing.JCheckBox();
        jCheckBoxConsertado = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jFTFValor = new javax.swing.JFormattedTextField();
        jButtonBusca = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        selectMetodoDePagamento = new javax.swing.JComboBox<>();
        selectPeca = new javax.swing.JComboBox<>();
        lblPecasComProblema = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        textQuantidade = new javax.swing.JTextField();
        jFTFCPF = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServicos = new javax.swing.JTable();
        jButtonBuscarCPF = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Serviços");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Serviço");

        jTFCliente.setEnabled(false);

        jLabel2.setText("Cliente");

        jLabel3.setText("Veículo");

        jTFVeiculo.setEnabled(false);

        jLabel4.setText("CPF");

        jCheckBoxPago.setText("Pago");
        jCheckBoxPago.setEnabled(false);

        jCheckBoxConsertado.setText("Consertado");
        jCheckBoxConsertado.setEnabled(false);

        jLabel6.setText("Valor");

        jFTFValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFTFValor.setEnabled(false);

        jButtonBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/zoom.png"))); // NOI18N
        jButtonBusca.setToolTipText("Pesquisar cliente");
        jButtonBusca.setBorderPainted(false);
        jButtonBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaActionPerformed(evt);
            }
        });

        jLabel8.setText("Método de pagamento");

        selectMetodoDePagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Dinheiro", "PIX", "Débito", "Crédito" }));
        selectMetodoDePagamento.setEnabled(false);

        selectPeca.setEnabled(false);
        selectPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPecaActionPerformed(evt);
            }
        });

        lblPecasComProblema.setText("Adicionar peças com problema");

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/cog_add.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setToolTipText("Adicionar peça com problema");
        btnAdicionar.setEnabled(false);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        textQuantidade.setEnabled(false);
        textQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQuantidadeActionPerformed(evt);
            }
        });

        try {
            jFTFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(selectPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAdicionar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblPecasComProblema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFVeiculo, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTFValor)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jCheckBoxConsertado)
                                        .addComponent(jCheckBoxPago)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(selectMetodoDePagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBusca)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTFValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jCheckBoxPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxConsertado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblPecasComProblema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectMetodoDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar)
                    .addComponent(textQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTableServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Veículo", "Funcionário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableServicos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableServicos);
        if (jTableServicos.getColumnModel().getColumnCount() > 0) {
            jTableServicos.getColumnModel().getColumn(0).setResizable(false);
            jTableServicos.getColumnModel().getColumn(1).setResizable(false);
            jTableServicos.getColumnModel().getColumn(2).setResizable(false);
            jTableServicos.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonBuscarCPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/vcardsearch.png"))); // NOI18N
        jButtonBuscarCPF.setText("Buscar por CPF");
        jButtonBuscarCPF.setToolTipText("Habilitar pesquisa de cliente por CPF");
        jButtonBuscarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCPFActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/vcard_delete.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setToolTipText("Excluir serviço");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/accept.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Salvar edições");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setToolTipText("Voltar para menu principal");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/cancel.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Limpar todos os campos");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBuscarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscarCPF)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVoltar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCPFActionPerformed
        // TODO add your handling code here:
        jFTFCPF.setEnabled(true);
        jButtonBusca.setEnabled(true);
    }//GEN-LAST:event_jButtonBuscarCPFActionPerformed

    private void jButtonBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaActionPerformed
        String cpf = jFTFCPF.getText();                
        boolean encontrado = false;
        if (cpf.isBlank() || cpf.isEmpty() || cpf.contains("   .   .   -  ")){
            JOptionPane.showMessageDialog(null, "Insira um CPF!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        else {
            for (int i = 0; i < Objetos.clientes.size(); i++){
                if (Objetos.clientes.get(i) != null){
                    if (Objetos.clientes.get(i).getCpf().equals(cpf)){
                        cliente = Objetos.clientes.get(i);
                        encontrado = true;
                        break;
                    }                
                }
            }
            if (!encontrado){
                JOptionPane.showMessageDialog(null, "Não existe um cliente com esse CPF!", "ERRO", JOptionPane.ERROR_MESSAGE);
            } else {
                carregaTabelaServicos(true);
            }
        }                                        
    }//GEN-LAST:event_jButtonBuscaActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (jCheckBoxConsertado.isSelected()){            
            usuario.consertarVeiculo(servico, (String) selectMetodoDePagamento.getSelectedItem());
        }
        if (jCheckBoxPago.isSelected()){            
            servico.setPago(true);            
            double valor = servico.getCliente().getDebito() - Double.parseDouble(jFTFValor.getText());
            servico.getCliente().setDebito(valor);
        }
        if (selectMetodoDePagamento.getSelectedItem() != null){
            servico.setMetodoPagamento((String) selectMetodoDePagamento.getSelectedItem());
        }
        usuario.pegarPecasNoEstoque(servico);
        pecas.clear();
        javax.swing.JOptionPane.showMessageDialog(this, "Dados salvos com sucesso");
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (usuario.getServicosAtivos().get(servico) != null || usuario.isAdmin()) {
            int resposta = javax.swing.JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esse serviço?");
            if (resposta == JOptionPane.YES_OPTION) {
                if (!Objetos.servicos.isEmpty()){            
                    Objetos.servicos.remove(servico.getId());
                    javax.swing.JOptionPane.showMessageDialog(this, "Serviço excluído com sucesso");            
                    carregaTabelaServicos(false);
                    redefinirCampos();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Você não tem autorização para excluir esse serviço", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        TipoDePeca tipoDePeca = (TipoDePeca) selectPeca.getSelectedItem();
        int qtd = Integer.valueOf(textQuantidade.getText());
        pecas.add(new Peca(qtd, tipoDePeca));
        String metodo = (String) selectMetodoDePagamento.getSelectedItem();
        servico.adicionaPecasComProblema(pecas, metodo);
        jFTFValor.setText(String.format("%.2f", servico.getValor()));
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void textQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuantidadeActionPerformed

    private void selectPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectPecaActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaLogin.telaMain.carregarTabelaServicos();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:                                
        carregaTabelaServicos(false);
        redefinirCampos();
        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void preencherCampos(Servico servico){
        jTFCliente.setText(servico.getCliente().getNome());
        jTFVeiculo.setText(servico.getVeiculo().getModelo() + ' ' + servico.getVeiculo().getPlaca());
        jButtonExcluir.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jFTFCPF.setEnabled(true);
        jButtonBusca.setEnabled(true);
        selectPeca.setEnabled(true);
        textQuantidade.setEnabled(true);
        btnAdicionar.setEnabled(true);
        selectMetodoDePagamento.setEnabled(true);
        jCheckBoxConsertado.setEnabled(true);
        jCheckBoxPago.setEnabled(true);
                
        selectPeca.removeAllItems();
        selectPeca.addItem(new TipoDePeca());
        for (Peca peca : Estoque.getEstoque()) {
            selectPeca.addItem(peca.getTipoPeca());
        }

        jFTFValor.setText(String.format("%.2f", servico.getValor()));
        jCheckBoxPago.setSelected(servico.isPago());
        jCheckBoxConsertado.setSelected(servico.isConsertado());
        if (servico.getMetodoPagamento() != null){
            selectMetodoDePagamento.setSelectedItem(servico.getMetodoPagamento());
        }
    }
    
    public final void carregaTabelaServicos(boolean buscaCliente){                
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"ID","Cliente","Veículo", "Funcionário"} ,0);                
        
        for(int i = 0; i < Objetos.servicos.size() + 1; i++){
            if (Objetos.servicos.get(i) != null){
                if ((Objetos.servicos.get(i).getFuncionario().getId() == usuario.getId() || usuario.isAdmin())){
                    if (!buscaCliente){
                        Object linha[] = new Object[]{  Objetos.servicos.get(i).getId(),
                                            Objetos.servicos.get(i).getCliente().getCpf(),
                                            Objetos.servicos.get(i).getVeiculo().getModelo(),
                                            Objetos.servicos.get(i).getFuncionario().getCpf()
                                            };
                        modelo.addRow(linha);
                    } else if (cliente != null && Objetos.servicos.get(i).getCliente().equals(cliente)){
                        Object linha[] = new Object[]{  Objetos.servicos.get(i).getId(),
                                            Objetos.servicos.get(i).getCliente().getCpf(),
                                            Objetos.servicos.get(i).getVeiculo().getModelo(),
                                            Objetos.servicos.get(i).getFuncionario().getCpf()
                                            };
                        modelo.addRow(linha);
                    }                                        
                }                                
            }            
        }
        jTableServicos.setModel(modelo);
        jTableServicos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int selectedRow = jTableServicos.getSelectedRow();                
                if (selectedRow >= 0) {
                    int idServico = (Integer) jTableServicos.getValueAt(selectedRow, 0);
                    if (Objetos.servicos.get(idServico) != null){
                        servico = Objetos.servicos.get(idServico);
                        preencherCampos(servico);
                        jFTFCPF.setText(servico.getCliente().getCpf());
                        jButtonCancelar.setEnabled(true);
                    }                    
                }
            }
        });
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
    }
    
    private void redefinirCampos(){
        jTFCliente.setEnabled(false);
        jTFCliente.setText("");
        jFTFValor.setEnabled(false);
        jFTFValor.setText("");
        jTFVeiculo.setEnabled(false);
        jTFVeiculo.setText("");
        jCheckBoxPago.setEnabled(false);
        jCheckBoxPago.setSelected(false);
        jCheckBoxConsertado.setEnabled(false);
        jCheckBoxConsertado.setSelected(false);
        selectPeca.setEnabled(false);
        selectPeca.removeAll();
        textQuantidade.setEnabled(false);
        textQuantidade.setText("");
        btnAdicionar.setEnabled(false);
        selectMetodoDePagamento.setEnabled(false);
        selectMetodoDePagamento.removeAll();
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarServicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton jButtonBusca;
    private javax.swing.JButton jButtonBuscarCPF;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBoxConsertado;
    private javax.swing.JCheckBox jCheckBoxPago;
    private javax.swing.JFormattedTextField jFTFCPF;
    private javax.swing.JFormattedTextField jFTFValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCliente;
    private javax.swing.JTextField jTFVeiculo;
    private javax.swing.JTable jTableServicos;
    private javax.swing.JLabel lblPecasComProblema;
    private javax.swing.JComboBox<String> selectMetodoDePagamento;
    private javax.swing.JComboBox<TipoDePeca> selectPeca;
    private javax.swing.JTextField textQuantidade;
    // End of variables declaration//GEN-END:variables
}
