/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.ui;

import app.model.Cliente;
import app.model.Peca;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import app.model.Veiculo;
import app.utils.IDGeneratorCarro;
import app.utils.Objetos;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author derickandrade
 */
public class GerenciarClientes extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarClientes
     */
    private boolean flagEditar = false;
    private boolean flagAddVeiculo = false;
    private boolean flagEditarVeiculo = false;
    private ArrayList<Peca> arrayPeca = new ArrayList<>();
    
    public GerenciarClientes() {
        initComponents();
        carregarTabelaClientes();        
        excluirPecaComProblema();
        
        jComboBox1.setRenderer(new javax.swing.DefaultListCellRenderer() { 
                    @Override //Altera a forma que o objeto é exibido na combo box
                    public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                        super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                            if (value instanceof Veiculo veiculo) {            
                                setText(veiculo.getModelo() + ' ' + veiculo.getPlaca());  
                            }
                        return this;
                    }
        });       
        
        arrayPeca.clear();
        jTFid.setEnabled(false);
        jTFNome.setEnabled(false);
        jTFEmail.setEnabled(false);
        jFTFTelefone.setEnabled(false);
        jFTFDebito.setEnabled(false);
        jFTFTotalPago.setEnabled(false);
        jComboBox1.setEnabled(false);
        
        jTFidVeiculo.setEnabled(false);
        jTFTipo.setEnabled(false);
        jTFModelo.setEnabled(false);
        jFTFAno.setEnabled(false);
        jTFCor.setEnabled(false);
        jTablePecas.setEnabled(false);
        txtPlaca.setEnabled(false);
        
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonConfirmar.setEnabled(false);
        jButtonExcluirVeiculo.setEnabled(false);
        jButtonAddVeiculo.setEnabled(false);
        jButtonEditarVeiculo.setEnabled(false);
        jButtonOkVeiculo.setEnabled(false);
        //esses botões para fazer alterações só vão ficar disponíveis quando um cliente for pesquisado, a flag de edição e de admin forem true
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFTFCPF = new javax.swing.JFormattedTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTFid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFTFTelefone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFTFDebito = new javax.swing.JFormattedTextField();
        jFTFTotalPago = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTFidVeiculo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFTipo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFModelo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTFCor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePecas = new javax.swing.JTable();
        jFTFAno = new javax.swing.JFormattedTextField();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonAddVeiculo = new javax.swing.JButton();
        jButtonEditarVeiculo = new javax.swing.JButton();
        jButtonExcluirVeiculo = new javax.swing.JButton();
        jButtonOkVeiculo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Clientes");
        setResizable(false);

        jLabel1.setText("Nome");

        jLabel2.setText("CPF");

        try {
            jFTFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/zoom.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setToolTipText("Pesquisar cliente por CPF");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        jLabel4.setText("E-Mail");

        jLabel5.setText("Telefone");

        try {
            jFTFTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFTelefoneActionPerformed(evt);
            }
        });

        jLabel6.setText("Débito");

        jLabel7.setText("Total pago");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Veículos");

        jLabel9.setText("Dados do Cliente");

        jFTFDebito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jFTFTotalPago.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jFTFTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTFEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jFTFCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonPesquisar))
                        .addComponent(jTFNome, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTFTotalPago)
                    .addComponent(jComboBox1, 0, 100, Short.MAX_VALUE)
                    .addComponent(jTFid)
                    .addComponent(jFTFDebito)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jTFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel10.setText("Dados do Veículo");

        jLabel11.setText("ID");

        jLabel12.setText("Tipo");

        jLabel13.setText("Modelo");

        jLabel14.setText("Ano");

        jLabel15.setText("Cor");

        jLabel16.setText("Peças com problema");

        jTablePecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Marca", "Qtd."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePecas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTablePecas);
        if (jTablePecas.getColumnModel().getColumnCount() > 0) {
            jTablePecas.getColumnModel().getColumn(0).setResizable(false);
            jTablePecas.getColumnModel().getColumn(1).setResizable(false);
            jTablePecas.getColumnModel().getColumn(2).setResizable(false);
        }

        jFTFAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFTFAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFAnoActionPerformed(evt);
            }
        });

        lblPlaca.setText("Placa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(257, 257, 257))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jFTFAno, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTFidVeiculo)
                    .addComponent(jTFTipo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTFModelo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFCor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFidVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblPlaca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFTFAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/cancel.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Limpar todos os campos");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/user_edit.png"))); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.setToolTipText("Editar cliente");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/user_delete.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setToolTipText("Excluir cliente");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/accept.png"))); // NOI18N
        jButtonConfirmar.setText("OK");
        jButtonConfirmar.setToolTipText("Salvar edições");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonAddVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/car_add.png"))); // NOI18N
        jButtonAddVeiculo.setText("Adicionar");
        jButtonAddVeiculo.setToolTipText("Adicionar veículo");
        jButtonAddVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddVeiculoActionPerformed(evt);
            }
        });

        jButtonEditarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/car_edit.png"))); // NOI18N
        jButtonEditarVeiculo.setText("Editar");
        jButtonEditarVeiculo.setToolTipText("Editar veículo");
        jButtonEditarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarVeiculoActionPerformed(evt);
            }
        });

        jButtonExcluirVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/car_delete.png"))); // NOI18N
        jButtonExcluirVeiculo.setText("Excluir");
        jButtonExcluirVeiculo.setToolTipText("Excluir veículo");
        jButtonExcluirVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirVeiculoActionPerformed(evt);
            }
        });

        jButtonOkVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/accept.png"))); // NOI18N
        jButtonOkVeiculo.setText("OK");
        jButtonOkVeiculo.setToolTipText("Confirmar edição ou inclusão de veículo");
        jButtonOkVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkVeiculoActionPerformed(evt);
            }
        });

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "CPF", "Nome", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableClientes);
        if (jTableClientes.getColumnModel().getColumnCount() > 0) {
            jTableClientes.getColumnModel().getColumn(1).setResizable(false);
            jTableClientes.getColumnModel().getColumn(2).setResizable(false);
            jTableClientes.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setToolTipText("Voltar para menu principal");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonExcluirVeiculo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAddVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonEditarVeiculo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonOkVeiculo))
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jButtonAddVeiculo)
                    .addComponent(jButtonEditarVeiculo)
                    .addComponent(jButtonExcluirVeiculo)
                    .addComponent(jButtonOkVeiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVoltar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void excluirPecaComProblema(){
        // 1. Criar menu de contexto
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem deleteItem = new JMenuItem("Excluir");
        popupMenu.add(deleteItem);

        jTablePecas.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showPopup(e);
                }
            }
            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showPopup(e);
                }
            }
            private void showPopup(MouseEvent e) {
                int row = jTablePecas.rowAtPoint(e.getPoint());
                if (row >= 0 && row < jTablePecas.getRowCount()) {
                    jTablePecas.setRowSelectionInterval(row, row);
                    popupMenu.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
        
        deleteItem.addActionListener(e -> {
            int selectedRow = jTablePecas.getSelectedRow();
            if (selectedRow != -1) {
                // Verifica o conteúdo da primeira coluna
                String valorPrimeiraColuna = (String) jTablePecas.getValueAt(selectedRow, 0);
                if (!"Sem dados".equals(valorPrimeiraColuna)) {
                    Veiculo veiculo = (Veiculo) jComboBox1.getSelectedItem();
                    Peca pecaRemover;

                    // Verifica se a flagEditarVeiculo é verdadeira
                    if (flagEditarVeiculo) {
                        if (selectedRow < arrayPeca.size()) {
                            pecaRemover = arrayPeca.get(selectedRow);
                            arrayPeca.remove(pecaRemover);  // Remove do arrayPeca
                        }
                    } else {
                        if (veiculo != null && selectedRow < veiculo.getPecasComProblema().size()) {
                            pecaRemover = veiculo.getPecasComProblema().get(selectedRow);
                            veiculo.getPecasComProblema().remove(pecaRemover);  // Remove do Veículo
                        }
                    }

                    // Atualizar a exibição removendo a linha da tabela
                    DefaultTableModel model = (DefaultTableModel) jTablePecas.getModel();
                    model.removeRow(selectedRow);
                }
            }
        });
    }
    
    public final void carregarTabelaClientes(){
        //Criar o modelo da tabela
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"ID","CPF","Nome", "E-Mail", "Telefone", "Debito", "Total Pago"},0);
        for(int i = 1;i<Objetos.clientes.size() + 1;i++){
            if (Objetos.clientes.get(i) != null){
                Object linha[] = new Object[]{  Objetos.clientes.get(i).getId(),
                                            Objetos.clientes.get(i).getCpf(),
                                            Objetos.clientes.get(i).getNome(),
                                            Objetos.clientes.get(i).getEmail(),
                                            Objetos.clientes.get(i).getTelefone(),
                                            String.format("R$%.2f", Objetos.clientes.get(i).getDebito()),
                                            String.format("R$%.2f", Objetos.clientes.get(i).getTotalPago())                                            
                                            };
                modelo.addRow(linha);
            }            
        }
        jTableClientes.setModel(modelo);
        jTableClientes.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int selectedRow = jTableClientes.getSelectedRow();                
                if (selectedRow >= 0) {
                    int idCliente = (Integer) jTableClientes.getValueAt(selectedRow, 0);
                    Cliente clienteSelecionado = Objetos.clientes.get(idCliente);
                    preencherCampos(clienteSelecionado);
                }
            }
        });
    }
    
    public void carregarTabelaPecas(){
        
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Tipo","Marca","Qnt."},0);
        Veiculo veiculo = (Veiculo)jComboBox1.getSelectedItem();
        if (veiculo.getPecasComProblema().isEmpty()) {
            modelo.addRow(new Object[]{"Sem dados", "Sem dados", "0"});
        }
        else{
            for(Peca peca : veiculo.getPecasComProblema()){
            Object linha[] = new Object[]{  peca.getTipoPeca().getTipo(),
                                            peca.getTipoPeca().getMarca(),
                                            //peca.getTipoPeca().getQnt(),
                                            };
            modelo.addRow(linha);            
            }
        }        
        jTablePecas.setModel(modelo);
    }
    
    private void selecionarVeiculo(){
        //Carrega as informações do veículo que está na combobox, se houver algum
        if (jComboBox1.getItemCount() > 0){
            Veiculo veiculoSelecionado = (Veiculo)jComboBox1.getSelectedItem();
            jTFidVeiculo.setText(Integer.toString(veiculoSelecionado.getId()));
            jTFTipo.setText(veiculoSelecionado.getTipo());
            jTFModelo.setText(veiculoSelecionado.getModelo());
            jFTFAno.setText(Integer.toString(veiculoSelecionado.getAno()));
            jTFCor.setText(veiculoSelecionado.getCor());            
            txtPlaca.setText(veiculoSelecionado.getPlaca());
        }
    }
    
    public void carregaVeiculos(){       
        //Verifica se o índice está nos map e se o array de veículos do cliente está vazio
        if (Objetos.clientes.containsKey(Integer.valueOf(jTFid.getText()))){
            Cliente cliente = Objetos.clientes.get(Integer.valueOf(jTFid.getText()));                        
            if (!cliente.getVeiculos().isEmpty()){
                ArrayList<Veiculo> veiculos = cliente.getVeiculos();                
                //Se tiver algum veículo, carrega as informações dele
                for (Veiculo veiculo : veiculos) { 
                    jComboBox1.addItem(veiculo);
                }
                //Se tiver algum veículo cadastrado, os botões de editar e excluir veículo ficam disponíveis  
                if (!veiculos.isEmpty()) {                        
                    jButtonEditarVeiculo.setEnabled(true);
                    jButtonExcluirVeiculo.setEnabled(true);
                    jComboBox1.setEnabled(true);
                }
            }
        }                
    }
    
    public void resetaCamposCliente(){                
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonConfirmar.setEnabled(false);
        
        jTFid.setText("");
        
        jButtonPesquisar.setEnabled(true);
        jFTFCPF.setEnabled(true);
        jFTFCPF.setText("");
        
        jTFNome.setEnabled(false);
        jTFNome.setText("");
        
        jTFEmail.setEnabled(false);
        jTFEmail.setText("");
        
        jFTFTelefone.setEnabled(false);
        jFTFTelefone.setText("");
        
        jFTFDebito.setEnabled(false);
        jFTFDebito.setText("");
        
        jFTFTotalPago.setEnabled(false);
        jFTFTotalPago.setText("");
        
        jComboBox1.setEnabled(false);
        jComboBox1.removeAllItems();
    }
    
    public void resetaCamposVeiculo(){
        jTFidVeiculo.setText("");
        
        jTFTipo.setEnabled(false);
        jTFTipo.setText("");
        
        jTFModelo.setEnabled(false);
        jTFModelo.setText("");
        
        jFTFAno.setEnabled(false);
        jFTFAno.setText("");
        
        jTFCor.setEnabled(false);
        jTFCor.setText("");
        
        jTablePecas.setEnabled(false);
        jTablePecas.removeAll();
        
        txtPlaca.setEnabled(false);
        txtPlaca.setText("");
        
        jTablePecas.setEnabled(false);
        DefaultTableModel modelo = (DefaultTableModel) jTablePecas.getModel();
        modelo.setRowCount(0);
        
        jButtonEditarVeiculo.setEnabled(false);
        jButtonAddVeiculo.setEnabled(false);
        jButtonExcluirVeiculo.setEnabled(false);
        jButtonOkVeiculo.setEnabled(false);
    }
    
    public void limpaTudo(){
        flagEditar = false;
        flagAddVeiculo = false;
        flagEditarVeiculo = false;
        
        resetaCamposCliente();
        
        resetaCamposVeiculo();
    }
    
    private void editVeiculoState(){
        //Campos do cliente
        jFTFCPF.setEnabled(false);
        jFTFTelefone.setEnabled(false);
        jFTFDebito.setEnabled(false);
        jFTFTotalPago.setEnabled(false);
        jTFNome.setEnabled(false);
        jTFEmail.setEnabled(false);
        jComboBox1.setEnabled(false);        
        jButtonPesquisar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonConfirmar.setEnabled(false);
        
        //Campos do veículo
        jTFTipo.setEnabled(true);
        jFTFAno.setEnabled(true);
        jTFCor.setEnabled(true);
        jTFModelo.setEnabled(true);
        jTablePecas.setEnabled(true);
        txtPlaca.setEnabled(true);
        
        jButtonExcluirVeiculo.setEnabled(false);
        jButtonAddVeiculo.setEnabled(false);
        jButtonOkVeiculo.setEnabled(true);
    }
    private void preencherCampos(Cliente cliente){
        flagEditar = false;
        flagAddVeiculo = false;
        flagEditarVeiculo = false;
        jFTFCPF.setText(cliente.getCpf());
        jTFNome.setText(cliente.getNome());
        jTFEmail.setText(cliente.getEmail());
        jFTFTelefone.setText(cliente.getTelefone());
        jTFid.setText(Integer.toString(cliente.getId()));
        jFTFDebito.setText(String.format("%.2f", cliente.getDebito()));
        jFTFTotalPago.setText(String.format("%.2f", cliente.getTotalPago()));
        jComboBox1.removeAllItems();
        if (!cliente.getVeiculos().isEmpty()){
            carregaVeiculos();
        }                                                         
        jButtonExcluir.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonAddVeiculo.setEnabled(true);
    }
    
    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:        
        flagEditar = false;
        flagEditarVeiculo = false;
        flagAddVeiculo = false;
        jButtonConfirmar.setEnabled(false);
        boolean encontrado = false;
        if (jFTFCPF.getText().equals("   .   .   -  ")){          //verifica se o cpf está vazio
            javax.swing.JOptionPane.showMessageDialog(this, "Informe um CPF!");
        }
        else {                  
            for (int i = 1; i < Objetos.clientes.size() + 1; i++){
                if (Objetos.clientes.get(i) != null){
                    if (Objetos.clientes.get(i).getCpf().equals(jFTFCPF.getText())) { //percorre o array de clientes até encontrar o CPF e colocar os dados nos respectivos campos
                    encontrado = true;
                    Cliente cliente = Objetos.clientes.get(i);
                    preencherCampos(cliente);                  
                    break;
                    }
                }
            }
            if (!encontrado){
                javax.swing.JOptionPane.showMessageDialog(this, "Cliente não encontrado!");                
            }
        }               
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        flagEditar = true;
        
        jButtonExcluir.setEnabled(false);               
        jComboBox1.setEnabled(false);
        jButtonExcluirVeiculo.setEnabled(false);
        jButtonAddVeiculo.setEnabled(false);
        jButtonEditarVeiculo.setEnabled(false);
        
        //Apenas campos de texto do cliente e botão confirmar fica disponíveis nesse estado
        jTFNome.setEnabled(true);
        jTFEmail.setEnabled(true);
        jFTFTelefone.setEnabled(true);
        jFTFDebito.setEnabled(true);
        jFTFTotalPago.setEnabled(true);
        jButtonConfirmar.setEnabled(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:
        if (flagEditar){            //atribui todos os novos valores com base no ID como índice do array de clientes, reseta a flag de edição e o botão de confirmar
            int idInt = Integer.parseInt(jTFid.getText());                                                
            Objetos.clientes.get(idInt).setNome(jTFNome.getText());
            Objetos.clientes.get(idInt).setCpf(jFTFCPF.getText());
            Objetos.clientes.get(idInt).setEmail(jTFEmail.getText());
            Objetos.clientes.get(idInt).setTelefone(jFTFTelefone.getText());
            Objetos.clientes.get(idInt).setDebito(Double.parseDouble(jFTFDebito.getText()));
            Objetos.clientes.get(idInt).setTotalPago(Double.parseDouble(jFTFTotalPago.getText()));
            javax.swing.JOptionPane.showMessageDialog(this, "Dados alterados com sucesso.");
            flagEditar = false;                     
            
            //Se tiver algum veículo, a edição e exclusão de veículos fica disponível
            if (!Objetos.clientes.get(idInt).getVeiculos().isEmpty()){
                jButtonExcluirVeiculo.setEnabled(true);
                jButtonEditarVeiculo.setEnabled(true);
            }
            
        }
        jButtonConfirmar.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jTFNome.setEnabled(false);
        jTFEmail.setEnabled(false);
        jFTFTelefone.setEnabled(false);
        jFTFDebito.setEnabled(false);
        jFTFTotalPago.setEnabled(false);
        
        jButtonAddVeiculo.setEnabled(true);        
        carregarTabelaClientes();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int resposta = javax.swing.JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esse cliente?");
        if (resposta == JOptionPane.YES_OPTION) {            
            int indice = Integer.parseInt(jTFid.getText());
            if (!Objetos.clientes.get(indice).getVeiculos().isEmpty()) {
                for (Veiculo veiculo : Objetos.clientes.get(indice).getVeiculos()){
                    if (!veiculo.getPecasComProblema().isEmpty()){
                        veiculo.esvaziarPecasComProblema();
                    }                                    
                }
                Objetos.clientes.get(indice).excluirVeiculos();
            }
            Cliente.addIdLivre(indice);
            Objetos.clientes.remove(indice);
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso.");
            limpaTudo();
            carregarTabelaClientes();
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        limpaTudo();
        //Limpa todos os campos e desativa as flags e os botões
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        selecionarVeiculo();  
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonAddVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddVeiculoActionPerformed
        // TODO add your handling code here:
        // A janela entra no modo de adicionar um veículo
        flagAddVeiculo = true;
        
        // Todos os campos da parte do cliente e os botões de excluir e editar veículo são desativados
        jFTFCPF.setEnabled(false);
        jTFNome.setEnabled(false);
        jTFEmail.setEnabled(false);
        jFTFTelefone.setEnabled(false);
        jFTFDebito.setEnabled(false);
        jFTFTotalPago.setEnabled(false);
        jComboBox1.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonConfirmar.setEnabled(false);
        
        jButtonAddVeiculo.setEnabled(false);
        jButtonExcluirVeiculo.setEnabled(false);
        jButtonEditarVeiculo.setEnabled(false);
        
        //Os campos do veículo e botão OK são ativados
        jTFTipo.setEnabled(true);
        jTFTipo.setText("");
        jTFModelo.setEnabled(true);
        jTFModelo.setText("");        
        jFTFAno.setEnabled(true);
        jFTFAno.setText("");
        jTFCor.setEnabled(true);
        jTFCor.setText("");
        txtPlaca.setEnabled(true);
        txtPlaca.setText("");
        
        jTablePecas.setEnabled(true);
        DefaultTableModel model = (DefaultTableModel) jTablePecas.getModel();
        model.setRowCount(0);
        
        jButtonOkVeiculo.setEnabled(true);    
        
        jTFidVeiculo.setText(Integer.toString(IDGeneratorCarro.generateCarroID()));
    }//GEN-LAST:event_jButtonAddVeiculoActionPerformed

    private void jButtonOkVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkVeiculoActionPerformed
        // TODO add your handling code here:
        if (flagAddVeiculo){                                    
            if (jTFidVeiculo.getText().isEmpty() || jFTFAno.getText().isEmpty() ||jTFTipo.getText().isEmpty() ||jTFModelo.getText().isEmpty() ||jTFCor.getText().isEmpty()){
                javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
            }
            else {
                Veiculo novoVeiculo = new Veiculo(Integer.parseInt(jFTFAno.getText()), jTFTipo.getText(), txtPlaca.getText(), jTFModelo.getText(), jTFCor.getText());
                if (Objetos.clientes.containsKey(Integer.valueOf(jTFid.getText()))){
                    Cliente clienteAtual = Objetos.clientes.get(Integer.valueOf(jTFid.getText()));
                    clienteAtual.setVeiculo(novoVeiculo);
                    flagAddVeiculo = false;
                    javax.swing.JOptionPane.showMessageDialog(this, "Veículo cadastrado com sucesso!");

                    jFTFCPF.setEnabled(true);                
                    jTFTipo.setEnabled(false);
                    jFTFAno.setEnabled(false);
                    jTFCor.setEnabled(false);
                    jTFModelo.setEnabled(false);

                    jButtonExcluir.setEnabled(true);
                    jButtonEditar.setEnabled(true);
                    jButtonAddVeiculo.setEnabled(true);
                    jButtonEditarVeiculo.setEnabled(true);
                    jButtonPesquisar.setEnabled(true);
                    jComboBox1.setEnabled(true);

                    jButtonOkVeiculo.setEnabled(false);
                    jButtonExcluirVeiculo.setEnabled(true);
                    jComboBox1.addItem(novoVeiculo);
                    jComboBox1.setSelectedItem(novoVeiculo);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Índice inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }                
        }
        else if (flagEditarVeiculo){           
            if (jFTFAno.getText().isEmpty() || jTFCor.getText().isEmpty() || jTFModelo.getText().isEmpty() || jTFTipo.getText().isEmpty()){
                javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
            }
            else {                
                Veiculo veiculo = (Veiculo)jComboBox1.getSelectedItem();
                if (veiculo != null){
                    veiculo.setAno(Integer.parseInt(jFTFAno.getText()));
                    veiculo.setCor(jTFCor.getText());
                    veiculo.setTipo(jTFTipo.getText());
                    veiculo.setModelo(jTFModelo.getText());
                    javax.swing.JOptionPane.showMessageDialog(this, "Dados editados com sucesso.");

                    flagEditarVeiculo = false;
                    jFTFCPF.setEnabled(true);
                    jButtonPesquisar.setEnabled(true);
                    jButtonExcluir.setEnabled(true);
                    jButtonEditar.setEnabled(true);
                    jButtonExcluirVeiculo.setEnabled(true);
                    jButtonAddVeiculo.setEnabled(true);
                    jButtonEditarVeiculo.setEnabled(true);
                    jButtonOkVeiculo.setEnabled(false);
                    jComboBox1.setEnabled(true);

                    jTFTipo.setEnabled(false);
                    jFTFAno.setEnabled(false);
                    txtPlaca.setEnabled(false);
                    jTFCor.setEnabled(false);
                    jTFModelo.setEnabled(false);
                    jTablePecas.setEnabled(false);
                }            
            }                
        }
    }//GEN-LAST:event_jButtonOkVeiculoActionPerformed

    private void jButtonEditarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarVeiculoActionPerformed
        // TODO add your handling code here:
        flagEditarVeiculo = true;
        editVeiculoState();
    }//GEN-LAST:event_jButtonEditarVeiculoActionPerformed

    private void jButtonExcluirVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirVeiculoActionPerformed
        // TODO add your handling code here:
        int resposta = javax.swing.JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esse veículo?");
        if (resposta == JOptionPane.YES_OPTION) {
            int indice = Integer.parseInt(jTFid.getText());            
            if (!((Veiculo) jComboBox1.getSelectedItem()).getPecasComProblema().isEmpty()){
                ((Veiculo) jComboBox1.getSelectedItem()).esvaziarPecasComProblema();
            }                
            Objetos.clientes.get(indice).excluirVeiculo(((Veiculo)jComboBox1.getSelectedItem()));            
            javax.swing.JOptionPane.showMessageDialog(this, "Veículo excluído com sucesso.");
            resetaCamposVeiculo();
            jComboBox1.removeAllItems();
            carregaVeiculos();
        }
    }//GEN-LAST:event_jButtonExcluirVeiculoActionPerformed

    private void jFTFTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFTelefoneActionPerformed

    private void jFTFAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFAnoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaLogin.telaMain.carregarTabelaClientes();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddVeiculo;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEditarVeiculo;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonExcluirVeiculo;
    private javax.swing.JButton jButtonOkVeiculo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<Veiculo> jComboBox1;
    private javax.swing.JFormattedTextField jFTFAno;
    private javax.swing.JFormattedTextField jFTFCPF;
    private javax.swing.JFormattedTextField jFTFDebito;
    private javax.swing.JFormattedTextField jFTFTelefone;
    private javax.swing.JFormattedTextField jFTFTotalPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFCor;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFTipo;
    private javax.swing.JTextField jTFid;
    private javax.swing.JTextField jTFidVeiculo;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTable jTablePecas;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
