/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.ui;

import app.model.Cliente;
import app.model.Funcionario;
import java.util.ArrayList;

/**
 *
 * @author henri
 */
public class Main extends javax.swing.JFrame {
    
    /**
     * Creates new form Main
     */
    
    public static ArrayList<Funcionario> funcionarios = new ArrayList<>();
    public static ArrayList<Cliente> clientes = new ArrayList<>();
    public static boolean isAdmin = false; //pra dar os privilégios de excluir/editar dados definida como true pra teste
    
    public Main() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        btnGetAdmin = new javax.swing.JButton();
        btnLeave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonCadastrarCliente = new javax.swing.JButton();
        jButtonGerenciarClientes = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnGerenciarFuncs = new javax.swing.JButton();
        jButtonCadastrarFuncionario = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnGerenciarPcs = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButtonCriarServico = new javax.swing.JButton();
        jButtonGerenciarServicos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tonhão Autopeças");

        jLabel1.setFont(new java.awt.Font("Noto Sans Mono", 1, 36)); // NOI18N
        jLabel1.setText("Tonhão Autopeças");

        btnGetAdmin.setText("Admin");
        btnGetAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAdminActionPerformed(evt);
            }
        });

        btnLeave.setText("Sair");
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/gear.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGetAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLeave)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGetAdmin)
                    .addComponent(btnLeave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Início", jPanel7);

        jButtonCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/user_add.png"))); // NOI18N
        jButtonCadastrarCliente.setText("Cadastrar Cliente");
        jButtonCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarClienteActionPerformed(evt);
            }
        });

        jButtonGerenciarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/user_edit.png"))); // NOI18N
        jButtonGerenciarClientes.setText("Gerenciar Clientes");
        jButtonGerenciarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jButtonCadastrarCliente)
                .addGap(18, 18, 18)
                .addComponent(jButtonGerenciarClientes)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGerenciarClientes)
                    .addComponent(jButtonCadastrarCliente))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Clientes", jPanel4);

        btnGerenciarFuncs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/user_gray_edit.png"))); // NOI18N
        btnGerenciarFuncs.setText("Gerenciar Funcionários");
        btnGerenciarFuncs.setEnabled(false);
        btnGerenciarFuncs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarFuncsActionPerformed(evt);
            }
        });

        jButtonCadastrarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/user_gray_add.png"))); // NOI18N
        jButtonCadastrarFuncionario.setText("Cadastrar Funcionário");
        jButtonCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jButtonCadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGerenciarFuncs)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarFuncionario)
                    .addComponent(btnGerenciarFuncs))
                .addGap(184, 184, 184))
        );

        jTabbedPane3.addTab("Funcionários", jPanel5);

        btnGerenciarPcs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/wrench_edit.png"))); // NOI18N
        btnGerenciarPcs.setText("Gerenciar Registro de Peças Automotivas");
        btnGerenciarPcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarPcsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(btnGerenciarPcs)
                .addGap(117, 117, 117))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btnGerenciarPcs)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Peças", jPanel6);

        jButtonCriarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/car_add.png"))); // NOI18N
        jButtonCriarServico.setText("Criar Serviço");
        jButtonCriarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarServicoActionPerformed(evt);
            }
        });

        jButtonGerenciarServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/car_edit.png"))); // NOI18N
        jButtonGerenciarServicos.setText("Gerenciar Serviços");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButtonCriarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGerenciarServicos)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCriarServico)
                    .addComponent(jButtonGerenciarServicos))
                .addGap(184, 184, 184))
        );

        jTabbedPane3.addTab("Serviços", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        private void btnGerenciarPcsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGerenciarPcsActionPerformed
        {//GEN-HEADEREND:event_btnGerenciarPcsActionPerformed
                CadastroTipoPeca telaGerenciamentoPecas = new CadastroTipoPeca();
		telaGerenciamentoPecas.setVisible(true);
        }//GEN-LAST:event_btnGerenciarPcsActionPerformed

        private void btnGerenciarFuncsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGerenciarFuncsActionPerformed
        {//GEN-HEADEREND:event_btnGerenciarFuncsActionPerformed
                GerenciarFuncionarios telaGerFuncionario = new GerenciarFuncionarios();
		telaGerFuncionario.setVisible(true);
        }//GEN-LAST:event_btnGerenciarFuncsActionPerformed

        private void btnGetAdminActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGetAdminActionPerformed
        {//GEN-HEADEREND:event_btnGetAdminActionPerformed
		isAdmin = true;
		btnGerenciarFuncs.setEnabled(true);
        }//GEN-LAST:event_btnGetAdminActionPerformed

        private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLeaveActionPerformed
        {//GEN-HEADEREND:event_btnLeaveActionPerformed
                this.dispose();
		TelaLogin novoLogin = new TelaLogin();
		novoLogin.setVisible(true);
        }//GEN-LAST:event_btnLeaveActionPerformed

    private void jButtonCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarClienteActionPerformed
        // TODO add your handling code here:
        CadastroCliente novoCadastroCliente = new CadastroCliente();
        novoCadastroCliente.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarClienteActionPerformed

    private void jButtonGerenciarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarClientesActionPerformed
        // TODO add your handling code here:
        GerenciarClientes novoGerenciarClientes = new GerenciarClientes();
        novoGerenciarClientes.setVisible(true);
    }//GEN-LAST:event_jButtonGerenciarClientesActionPerformed

    private void jButtonCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
        GerenciarFuncionarios novoGerenciarFuncionarios = new GerenciarFuncionarios();
        novoGerenciarFuncionarios.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarFuncionarioActionPerformed

    private void jButtonCriarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarServicoActionPerformed
        // TODO add your handling code here:
        CriarServico novoCriarServico = new CriarServico();
        novoCriarServico.setVisible(true);
    }//GEN-LAST:event_jButtonCriarServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerenciarFuncs;
    private javax.swing.JButton btnGerenciarPcs;
    private javax.swing.JButton btnGetAdmin;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton jButtonCadastrarCliente;
    private javax.swing.JButton jButtonCadastrarFuncionario;
    private javax.swing.JButton jButtonCriarServico;
    private javax.swing.JButton jButtonGerenciarClientes;
    private javax.swing.JButton jButtonGerenciarServicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
