/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.ui;

import app.model.Cliente;
import app.model.Funcionario;
import java.util.ArrayList;

/**
 *
 * @author henri
 */
public class Main extends javax.swing.JFrame {
    
    /**
     * Creates new form Main
     */
    
    public static ArrayList<Funcionario> funcionarios = new ArrayList<>();
    public static ArrayList<Cliente> clientes = new ArrayList<>();
    public static boolean isAdmin = false; //pra dar os privilégios de excluir/editar dados definida como true pra teste
    
    public Main() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents()
        {

                jLabel1 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                btnGerenciarPcs = new javax.swing.JButton();
                btnGerenciarFuncs = new javax.swing.JButton();
                btnGetAdmin = new javax.swing.JButton();
                btnLeave = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Noto Sans Mono", 1, 36)); // NOI18N
                jLabel1.setText("Tonhão Autopeças");

                jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciamento"));

                btnGerenciarPcs.setText("Gerenciar Registro de Peças Automotivas");
                btnGerenciarPcs.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnGerenciarPcsActionPerformed(evt);
                        }
                });

                btnGerenciarFuncs.setText("Gerenciar Funcionários");
                btnGerenciarFuncs.setEnabled(false);
                btnGerenciarFuncs.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnGerenciarFuncsActionPerformed(evt);
                        }
                });

                btnGetAdmin.setText("Admin");
                btnGetAdmin.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnGetAdminActionPerformed(evt);
                        }
                });

                btnLeave.setText("Sair");
                btnLeave.addActionListener(new java.awt.event.ActionListener()
                {
                        public void actionPerformed(java.awt.event.ActionEvent evt)
                        {
                                btnLeaveActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(btnGetAdmin)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnLeave))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnGerenciarPcs)
                                                        .addComponent(btnGerenciarFuncs))
                                                .addGap(0, 160, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnGerenciarPcs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGerenciarFuncs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnGetAdmin)
                                        .addComponent(btnLeave))
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel1)
                                .addContainerGap(100, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void btnGerenciarPcsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGerenciarPcsActionPerformed
        {//GEN-HEADEREND:event_btnGerenciarPcsActionPerformed
                CadastroPeca telaGerenciamentoPecas = new CadastroPeca();
		telaGerenciamentoPecas.setVisible(true);
        }//GEN-LAST:event_btnGerenciarPcsActionPerformed

        private void btnGerenciarFuncsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGerenciarFuncsActionPerformed
        {//GEN-HEADEREND:event_btnGerenciarFuncsActionPerformed
                GerenciarFuncionarios telaGerFuncionario = new GerenciarFuncionarios();
		telaGerFuncionario.setVisible(true);
        }//GEN-LAST:event_btnGerenciarFuncsActionPerformed

        private void btnGetAdminActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGetAdminActionPerformed
        {//GEN-HEADEREND:event_btnGetAdminActionPerformed
		isAdmin = true;
		btnGerenciarFuncs.setEnabled(true);
        }//GEN-LAST:event_btnGetAdminActionPerformed

        private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLeaveActionPerformed
        {//GEN-HEADEREND:event_btnLeaveActionPerformed
                this.dispose();
		TelaLogin novoLogin = new TelaLogin();
		novoLogin.setVisible(true);
        }//GEN-LAST:event_btnLeaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnGerenciarFuncs;
        private javax.swing.JButton btnGerenciarPcs;
        private javax.swing.JButton btnGetAdmin;
        private javax.swing.JButton btnLeave;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel3;
        // End of variables declaration//GEN-END:variables
}
